import type { Metadata } from "next";
import Nav from "@/components/Nav";
import Hero from "@/components/ownership-report/Hero";
import DefinitionBlock from "@/components/ownership-report/DefinitionBlock";
import UrgencyBand from "@/components/ownership-report/UrgencyBand";
import Problem from "@/components/ownership-report/Problem";
import WhatsInside from "@/components/ownership-report/WhatsInside";
import HowItWorks from "@/components/ownership-report/HowItWorks";
import DesignedToImprove from "@/components/ownership-report/DesignedToImprove";
import WhoItsFor from "@/components/ownership-report/WhoItsFor";
import Pricing from "@/components/ownership-report/Pricing";
import FAQ from "@/components/ownership-report/FAQ";
import FinalCTA from "@/components/ownership-report/FinalCTA";
import Footer from "@/components/Footer";

const PAGE_URL = "https://www.stitchhospitality.com/";

export const metadata: Metadata = {
  title: "The GM Ownership Report OS — USALI 12 Ownership Reports, by a Sitting GM",
  description:
    "An operator-built ownership-reporting system designed for USALI 12th Revised Edition (effective Jan 1, 2026). PDF playbook, 8-tab Excel workbook with a restatement engine, Word template, and prompt library. Built by a sitting GM. From $29. Independent — not affiliated with HFTP.",
  authors: [{ name: "Chris Suarez" }],
  keywords: [
    "USALI 12",
    "USALI 12th revised edition",
    "hotel ownership report",
    "GM ownership report",
    "hotel owner reporting",
    "USALI restatement",
    "hotel account reclassification",
    "hotel labor productivity reporting",
    "hotel variance analysis",
    "RevPAR index RGI MPI ARI",
    "hotel P&L narrative",
    "energy water waste reporting",
    "hotel asset management report",
    "monthly hotel ownership report template",
    "hotel owner reporting toolkit",
  ],
  robots: { index: true, follow: true },
  alternates: { canonical: PAGE_URL },
  openGraph: {
    type: "website",
    siteName: "Stitch Hospitality",
    title: "The GM Ownership Report OS — USALI 12, Built by a Sitting GM",
    description:
      "USALI 12 changed your report on January 1. The playbook, 8-tab workbook, Word template, and prompts to write ownership reports that survive the call — with a restatement engine you configure. From $29.",
    url: PAGE_URL,
    // og:image tags are auto-generated by src/app/opengraph-image.tsx — do not
    // add an `images` array here, it would produce a duplicate/conflicting tag.
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "The GM Ownership Report OS — USALI 12, by a Sitting GM",
    description:
      "An operator-built ownership-report system designed for USALI 12. Playbook + 8-tab workbook + Word template + prompts, with a restatement engine you configure. From $29.",
    // twitter:image is auto-generated by src/app/twitter-image.tsx
  },
};

const productJsonLd = {
  "@context": "https://schema.org",
  "@type": "Product",
  name: "The GM Ownership Report OS",
  brand: { "@type": "Brand", name: "Stitch Hospitality" },
  description:
    "An operator-built ownership-reporting system designed for the USALI 12th Revised Edition (effective January 1, 2026). Includes a PDF playbook, an 8-tab Excel workbook with a restatement engine the buyer configures with their own account mappings, a Word report template, and a prompt library. Built by a sitting hotel general manager. Independent product; not affiliated with or endorsed by HFTP.",
  category: "Hotel financial reporting / hospitality operations",
  author: { "@type": "Person", name: "Chris Suarez", jobTitle: "Hotel General Manager" },
  audience: {
    "@type": "Audience",
    audienceType: "Hotel general managers, directors of finance, hotel owners and asset managers",
  },
  offers: [
    {
      "@type": "Offer",
      name: "PDF Playbook",
      price: "29.00",
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      url: `${PAGE_URL}#pricing`,
    },
    {
      "@type": "Offer",
      name: "The Full OS",
      price: "99.00",
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      url: `${PAGE_URL}#pricing`,
    },
  ],
};

// Mirrors src/components/ownership-report/FAQ.tsx exactly — Google penalizes
// FAQPage schema whose Q&As aren't visible to users, so these must stay in sync.
const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "Is this designed for USALI 12th Revised Edition?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes — the whole system is designed around the changes in the 12th Edition, effective January 1, 2026: the account reclassifications, the expanded labor detail, the energy/water/waste reporting, and loyalty-cost treatment. It doesn't reproduce the standard itself — you apply your own licensed USALI mappings, and the workbook does the work around them.",
      },
    },
    {
      "@type": "Question",
      name: "I'm not an accountant. Can I use this?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes. The playbook is written by a GM for GMs — it's about judgment and narrative, not bookkeeping. The workbook does the calculations; you enter your numbers and your mappings, and it drafts the language.",
      },
    },
    {
      "@type": "Question",
      name: "What exactly do I download?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "The Full OS is a PDF playbook, an 8-tab Excel workbook, a Word report template, and a prompt library. The $29 tier is the PDF playbook and worked example.",
      },
    },
    {
      "@type": "Question",
      name: "Do I need any subscription or software?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "No. You need Excel (or Google Sheets/Numbers to import) and Word. You own the files outright — no subscription, no lock-in.",
      },
    },
    {
      "@type": "Question",
      name: "What am I licensed to do with the files?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Your purchase is a non-transferable license to use the files internally for a single property. It doesn't cover redistribution, resale, or use across multiple properties. A receipt is emailed for expensing. For portfolio/multi-property or management-company licensing, email chris@stitchhospitality.com.",
      },
    },
    {
      "@type": "Question",
      name: "What if it's not useful?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "14-day refund — reply to your receipt. Limited to one refund per customer, and not available once the files have been used in a client-facing or portfolio engagement.",
      },
    },
  ],
};

const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Stitch Hospitality",
  url: "https://www.stitchhospitality.com",
  logo: "https://www.stitchhospitality.com/logo.png",
  description:
    "Stitch Hospitality builds The GM Ownership Report OS — an operator-built playbook, workbook, Word template, and prompt library that helps hotel general managers write ownership reports designed for the USALI 12th Revised Edition.",
  sameAs: ["https://www.linkedin.com/company/stitchhospitality-com"],
};

export default function HomePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(productJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <Nav />
      <main>
        <Hero />
        <DefinitionBlock />
        <UrgencyBand />
        <Problem />
        <WhatsInside />
        <HowItWorks />
        <DesignedToImprove />
        <WhoItsFor />
        <Pricing />
        <FAQ />
        <FinalCTA />
      </main>
      <Footer />
    </>
  );
}
